### ISSUE TITLE
A Resource Page for the Community Website

### ISSUE THREAD

**Issue by yingmo55** [CodecademyCommunity/CodecademyCommunity.github.io#101]
## Purpose
What will this feature provide?

- A page with additional resources on programming and programming related topics

### Is your feature request related to a problem? Please describe.
It is not related to a problem.

## Proposed Solution
Create a new page with a list of resources.

### Describe alternatives you've considered (optional)
Making one & hosting it by myself, which may have the following problems: 
1. I only know a limited amount of resources
2. It's better to have people verify the resources 

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] Create a new page with a list of resource

## Additional context
Is it possible to use some form of markdown to HTML parser for easier maintaining the resource page?

**Comment by lyallstewart** [comment]
This is great, thanks! One thing it might be nice to consider is how we want to implement this, to me the option seems to be (excluding just manually hardwriting them):

- We could go along with something like the staff page and have a JSON file.
- Use some kind of MD parser as you mentioned and keep all resources in there.

Do you (and others) have any particular preference or other suggestions? Personally I'd lean towards the former since that's what we've got for the staff page but I don't have a strong preference. 😄
